### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by unhandyandy** [mitmath/18330#2]
Thanks for making this course available online!  I’m teaching an intro to numerical analysis at Indiana U, and using Matlab, but If I teach it again I’d be very interested in the possibility of using Julia instead.

But do you worry that, since Matlab is more or less the industry standard, that you might be doing students a disservice by using Julia instead?

**Comment by stevengj** [comment]
No, it hasn't been a concern.

The philosophy at MIT has always been to teach concepts more than languages.   We use whatever programming languages are convenient for teaching, and assume that students can translate the concepts to other languages as needed.  (For many years, the main computer science courses used Scheme and CLU.)  This is doubly true for a numerical analysis course where the focus is not on software engineering per se.

We like teaching in Julia in part because we've been transitioning to that language in our own research and like it for technical computing.   Pedagogically, it allows us to do things that would be much more awkward in Matlab, e.g. dual numbers for automatic differentiation.  Also, the fact that Matlab (and Python/Numpy, R, etcetera) are slow for non-vectorized code tends to artificially push you towards a vectorized coding style rather than using the coding style that is most natural for a given problem. Also, much of the key source code for Julia and its libraries is written in Julia, which makes it easier to show students what is happening under the hood, as opposed to Matlab (where much of the code is not revealed) and Python/Numpy/Scipy (where many core operations are in C or Fortran).

(That being said, for some semesters a course like 18.330 may be taught in Python or Matlab simply because the instructor is more familiar with that language.   Course materials are easy to translate for the most part.)

**Comment by unhandyandy** [comment]
Thanks.  I probably should not assume the same prerogatives at IU.
